version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 13.4.1
      resource_class: medium

    steps:
      - checkout
      - run:
          name: Update bundle
          command: |
            sudo bundle update
      - run:
          name: Execute unit tests with fastlane
          command: |
            bundle exec fastlane unit_tests

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  build-test:
    jobs:
      - build-and-test
